// demos/vue/src/pages/copy.vue
<template>
  <div style="display: flex; justify-content: stretch; margin-top: 50px; margin-right: 50px">
    <div style="margin-left: 50px; flex: 1">
      <Container behaviour="copy" group-name="1" :get-child-payload="getChildPayload1">
        <Draggable v-for="item in items1" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
    <div style="margin-left: 50px; flex: 1">
      <Container group-name="1" :get-child-payload="getChildPayload2" @drop="onDrop('items2', $event)">
        <Draggable v-for="item in items2" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
    <div style="margin-left: 50px; flex: 1">
      <Container group-name="1" :get-child-payload="getChildPayload3" @drop="onDrop('items3', $event)">
        <Draggable v-for="item in items3" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
  </div>
</template>

<script>
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems } from '../utils/helpers'

export default {
  name: 'Copy',

  components: {Container, Draggable},

  data () {
    return {
      items1: generateItems(15, i => ({
        id: '1' + i,
        data: `Source Draggable - ${i}`
      })),
      items2: generateItems(15, i => ({
        id: '2' + i,
        data: `Draggable 2 - ${i}`
      })),
      items3: generateItems(15, i => ({
        id: '3' + i,
        data: `Draggable 3 - ${i}`
      }))
    }
  },

  methods: {
    onDrop (collection, dropResult) {
      this[collection] = applyDrag(this[collection], dropResult)
    },

    getChildPayload1 (index) {
      return this.items1[index]
    },

    getChildPayload2 (index) {
      return this.items2[index]
    },

    getChildPayload3 (index) {
      return this.items3[index]
    }
  }
}
</script>

// demos/react/src/pages/copy.tsx
import { Component } from 'react';
import { Container, Draggable } from '@likelylogic/react-smooth-dnd';
import { applyDrag, generateItems } from './utils.js';

const groupStyle = {
  marginLeft: '50px',
  flex: 1
}

class Copy extends Component {
  constructor(props) {
    super(props);

    this.state = {
      items1: generateItems(15, (i) => ({ id: '1' + i, data: `Source Draggable - ${i}` })),
      items2: generateItems(15, (i) => ({ id: '2' + i, data: `Draggable 2 - ${i}` })),
      items3: generateItems(15, (i) => ({ id: '3' + i, data: `Draggable 3 - ${i}` })),
      items4: generateItems(15, (i) => ({ id: '4' + i, data: `Draggable 4 - ${i}` })),
    }
  }
  render() {
    return (
      <div style={{ display: 'flex', justifyContent: 'stretch', marginTop: '50px', marginRight: '50px' }}>
        <div style={groupStyle}>
          <Container groupName="1" behaviour="copy" getChildPayload={i => this.state.items1[i]} onDrop={e => this.setState({ items1: applyDrag(this.state.items1, e) })}>
            {
              this.state.items1.map((p,i) => {
                return (
                  <Draggable key={i}>
                    <div className="draggable-item">
                      {p.data}
                    </div>
                  </Draggable>
                );
              })
            }
          </Container>
        </div>
        <div style={groupStyle}>
          <Container groupName="1" getChildPayload={i => this.state.items2[i]} onDrop={e => this.setState({ items2: applyDrag(this.state.items2, e) })}>
            {
              this.state.items2.map((p, i) => {
                return (
                  <Draggable key={i}>
                    <div className="draggable-item">
                      {p.data}
                    </div>
                  </Draggable>
                );
              })
            }
          </Container>
        </div>        
        <div style={groupStyle}>
          <Container groupName="1" getChildPayload={i => this.state.items3[i]} onDrop={e => this.setState({ items3: applyDrag(this.state.items3, e) })}>
            {
              this.state.items3.map(p => {
                return (
                  <Draggable key={p.id}>
                    <div className="draggable-item">
                      {p.data}
                    </div>
                  </Draggable>
                );
              })
            }
          </Container>
        </div>        
      </div>
    );
  }
}

export default Copy;
