// demos/vue/src/pages/drop-zone.vue
<template>
  <div class="drop-zone">
    <div
      v-for="(occupied, index) in zones"
      :key="index"
      :class="['drop-zone-container', classes[index]]"
    >
      <Container
        style="height: 100%"
        group-name="1"
        behaviour="drop-zone"
        @drop="onDrop(index, $event)"
        @drag-enter="dragEnter(index)"
        @drag-leave="dragLeave(index)"
      >
        <Draggable v-if="occupied">
          <div class="drop-zone-draggable">
            Draggable
          </div>
        </Draggable>
      </Container>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import type { DragResult } from '@demo/shared'

const zones = ref<number[]>([1, 0, 0, 0])
const classes = ref<string[]>(['', '', '', ''])

function onDrop (containerIndex: number, dropResult: DragResult) {
  const { addedIndex, removedIndex } = dropResult

  if (addedIndex !== null || removedIndex !== null) {
    if (removedIndex !== null) {
      zones.value[containerIndex] = 0
    }
    if (addedIndex !== null) {
      zones.value[containerIndex] = 1
    }
  }

  classes.value[containerIndex] = ''
}

function dragEnter (index: number) {
  classes.value[index] = 'hover'
}

function dragLeave (index: number) {
  classes.value[index] = ''
}
</script>

// demos/react/src/pages/drop-zone.tsx
import { Component } from 'react';
import { Container, Draggable } from '@likelylogic/react-smooth-dnd';
import { applyDrag, generateItems } from './utils.js';


class DropZone extends Component {
	constructor(props) {
		super(props);
		this.onDrop = this.onDrop.bind(this);
		this.dragEnter = this.dragEnter.bind(this);
		this.dragLeave = this.dragLeave.bind(this);

		this.state = {
			zones: [1, 0, 0, 0],
			classes: ['', '', '', '']
		};
	}
	render() {
		return (
			<div className="drop-zone">
				{this.state.zones.map((p, i) => {
					return (
						<div key={i} className={`drop-zone-container ${this.state.classes[i]}`}>
							<Container
								style={{ height: '100%' }}
								groupName="1"
								behaviour="drop-zone"
								onDrop={e => this.onDrop(i, e)}
								onDragEnter={() => this.dragEnter(i)}
								onDragLeave={() => this.dragLeave(i)}>
								{p ? (
									<Draggable>
										<div className="drop-zone-draggable">
											Draggable
									</div>
									</Draggable>
								) : null}
							</Container>
						</div>
					);
				})}
			</div>
		);
	}

	onDrop(containerIndex, dropresult) {
		const { addedIndex, removedIndex, payload } = dropresult;
		if (addedIndex !== null || removedIndex !== null) {
			const zones = [...this.state.zones];
			if (removedIndex !== null) {
				zones[containerIndex] = 0;
			}
			if (addedIndex !== null) {
				zones[containerIndex] = 1;
			}
			this.setState({
				zones
			});
		}

		const classes = [...this.state.classes];
		classes[containerIndex] = '';
		this.setState({
			classes
		});
	}

	dragEnter(i) {
		const classes = [...this.state.classes];
		classes[i] = 'hover';
		this.setState({
			classes
		});
	}

	dragLeave(i) {
		const classes = [...this.state.classes];
		classes[i] = '';
		this.setState({
			classes
		});
	}
}

export default DropZone;
