// demos/vue/src/pages/drop-out.vue
<template>
  <Container
    class="drop-out drop-target"
    :class="{ 'is-active': isOver }"
    group-name="drop-out"
    behaviour="drop-zone"
    @drop="onDropOut"
    @drag-enter="isOver = true"
    @drag-leave="isOver = false"
  >
    <!--
      Plain divs, not <Draggable>s. They are still counted as this container's
      children internally, but `behaviour: drop-zone` never sorts, and without
      the wrapper class a mousedown on them can't start a drag.
    -->
    <div class="drop-out__lists">
      <div
        v-for="(list, listIndex) in lists"
        :key="listIndex"
        class="drop-out__list"
        :class="{ 'is-active': activeList === listIndex }"
      >
        <h4 class="drop-label">List {{ listIndex + 1 }}</h4>
        <Container
          group-name="drop-out"
          :get-child-payload="index => lists[listIndex][index]"
          @drop="onDropInList(listIndex, $event)"
          @drag-enter="activeList = listIndex"
          @drag-leave="activeList = null"
        >
          <Draggable v-for="item in list" :key="item.id">
            <div class="draggable-item">{{ item.data }}</div>
          </Draggable>
        </Container>
      </div>
    </div>

    <div class="drop-out__aside">
      <h4 class="drop-label">
        Dropped out
        <button v-if="detached.length" class="drop-out__reset" @click="reset">reset</button>
      </h4>
      <p v-if="!detached.length" class="drop-out__hint">
        Drag an item off a list and release it anywhere in the dashed area.
      </p>
      <ul class="drop-out__detached">
        <li v-for="item in detached" :key="item.id">{{ item.data }}</li>
      </ul>

      <h4 class="drop-label">Drop events</h4>
      <ol class="drop-out__log">
        <li v-for="(entry, i) in log" :key="i">{{ entry }}</li>
      </ol>
    </div>
  </Container>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

interface Item {
  id: string
  data: string
}

function build () {
  return [
    generateItems<Item>(6, i => ({ id: `a${i}`, data: `Item A${i}` })),
    generateItems<Item>(6, i => ({ id: `b${i}`, data: `Item B${i}` })),
  ]
}

const lists = ref<Item[][]>(build())
const detached = ref<Item[]>([])
const isOver = ref(false)
const activeList = ref<number | null>(null)
const log = ref<string[]>([])

function note (message: string) {
  log.value = [message, ...log.value].slice(0, 8)
}

function onDropInList (listIndex: number, dropResult: DragResult) {
  activeList.value = null
  const { removedIndex, addedIndex } = dropResult
  if (removedIndex === null && addedIndex === null) {
    return
  }
  note(`list ${listIndex + 1} — removed: ${removedIndex}, added: ${addedIndex}`)
  lists.value[listIndex] = applyDrag(lists.value[listIndex], dropResult)
}

function onDropOut (dropResult: DragResult) {
  isOver.value = false

  // The surrounding zone fires for every drop, including ones that landed on a
  // list — those arrive with both indices null and are not ours to handle.
  if (dropResult.addedIndex === null) {
    return
  }

  note(`surround — added: ${dropResult.addedIndex} (always 0)`)
  if (dropResult.payload) {
    detached.value = [...detached.value, dropResult.payload as Item]
  }
}

function reset () {
  lists.value = build()
  activeList.value = null
  detached.value = []
  log.value = []
}
</script>

// demos/react/src/pages/drop-out.tsx
import { useCallback, useState } from 'react'
import { Container, Draggable } from '@likelylogic/react-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

interface Item {
  id: string
  data: string
}

function build (): Item[][] {
  return [
    generateItems<Item>(6, i => ({ id: `a${i}`, data: `Item A${i}` })),
    generateItems<Item>(6, i => ({ id: `b${i}`, data: `Item B${i}` })),
  ]
}

/**
 * A drop zone that surrounds the sortables, so an item can be dragged off a
 * list and released into empty space.
 *
 * The outer `behaviour: drop-zone` container wraps everything; `getPosition`
 * resolves to the innermost relevant container under the pointer, so a list
 * wins while you are over it and the surround takes over once you are not.
 */
export default function DropOut () {
  const [lists, setLists] = useState<Item[][]>(build)
  const [detached, setDetached] = useState<Item[]>([])
  const [isOver, setIsOver] = useState(false)
  const [activeList, setActiveList] = useState<number | null>(null)
  const [log, setLog] = useState<string[]>([])

  const note = useCallback((message: string) => {
    setLog(log => [message, ...log].slice(0, 8))
  }, [])

  const onDropInList = useCallback((listIndex: number, dropResult: DragResult) => {
    setActiveList(null)
    const { removedIndex, addedIndex } = dropResult
    if (removedIndex === null && addedIndex === null) {
      return
    }
    note(`list ${listIndex + 1} — removed: ${removedIndex}, added: ${addedIndex}`)
    setLists(lists => lists.map((list, i) => (
      i === listIndex ? applyDrag(list, dropResult) : list
    )))
  }, [note])

  const onDropOut = useCallback((dropResult: DragResult) => {
    setIsOver(false)

    // The surrounding zone fires for every drop, including ones that landed on
    // a list — those arrive with both indices null and are not ours to handle.
    if (dropResult.addedIndex === null) {
      return
    }

    note(`surround — added: ${dropResult.addedIndex} (always 0)`)
    if (dropResult.payload) {
      setDetached(detached => [...detached, dropResult.payload as Item])
    }
  }, [note])

  const reset = useCallback(() => {
    setLists(build())
    setActiveList(null)
    setDetached([])
    setLog([])
  }, [])

  return (
    <Container
      groupName="drop-out"
      behaviour="drop-zone"
      onDrop={onDropOut}
      onDragEnter={() => setIsOver(true)}
      onDragLeave={() => setIsOver(false)}
      // The React Container renders a bare div and drops className, so the
      // render prop is the way to style the root.
      render={ref => (
        <div ref={ref} className={`drop-out drop-target ${isOver ? 'is-active' : ''}`}>
          {/*
            Plain divs, not Draggables. They are still counted as this
            container's children internally, but drop-zone never sorts, and
            without the wrapper class a mousedown on them can't start a drag.
          */}
          <div className="drop-out__lists">
            {lists.map((list, listIndex) => (
              <div
                key={listIndex}
                className={`drop-out__list ${activeList === listIndex ? 'is-active' : ''}`}
              >
                <h4 className="drop-label">List {listIndex + 1}</h4>
                <Container
                  groupName="drop-out"
                  getChildPayload={index => lists[listIndex][index]}
                  onDrop={e => onDropInList(listIndex, e)}
                  onDragEnter={() => setActiveList(listIndex)}
                  onDragLeave={() => setActiveList(null)}
                >
                  {list.map(item => (
                    <Draggable key={item.id}>
                      <div className="draggable-item">{item.data}</div>
                    </Draggable>
                  ))}
                </Container>
              </div>
            ))}
          </div>

          <div className="drop-out__aside">
            <h4 className="drop-label">
              Dropped out
              {detached.length > 0 && (
                <button className="drop-out__reset" onClick={reset}>reset</button>
              )}
            </h4>
            {detached.length === 0 && (
              <p className="drop-out__hint">
                Drag an item off a list and release it anywhere in the dashed area.
              </p>
            )}
            <ul className="drop-out__detached">
              {detached.map(item => <li key={item.id}>{item.data}</li>)}
            </ul>

            <h4 className="drop-label">Drop events</h4>
            <ol className="drop-out__log">
              {log.map((entry, i) => <li key={i}>{entry}</li>)}
            </ol>
          </div>
        </div>
      )}
    />
  )
}
