// demos/vue/src/pages/simple.vue
<template>
  <div class="simple-page">
    <Container @drop="onDrop" :get-ghost-parent="getGhostParent" :remove-on-drop-out="true" @drop-ready="onDropReady">
      <Draggable v-for="item in items" :key="item.id">
        <div class="draggable-item">
          {{item.data}}
        </div>
      </Draggable>
    </Container>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

const items = ref(generateItems(50, i => ({ id: i, data: 'Draggable ' + i })))

function onDrop (dropResult: DragResult) {
  items.value = applyDrag(items.value, dropResult)
}

function getGhostParent () {
  return document.body
}

function onDropReady (dropResult: DragResult) {
  console.log('drop ready', dropResult)
}
</script>

// demos/react/src/pages/simple.tsx
import { useCallback, useState } from 'react'
import { Container, Draggable, type DropResult } from '@likelylogic/react-smooth-dnd'
import { applyDrag, generateItems } from '@demo/shared'

export interface Item {
  id: number
  data: string
}

/** The baseline demo: one container, default options. */
export default function Simple () {
  const [items, setItems] = useState<Item[]>(() => generateItems(50, index => ({
    id: index,
    data: 'Draggable' + index,
  })))

  const onDrop = useCallback((result: DropResult) => {
    setItems(items => applyDrag(items, result))
  }, [])

  return (
    <div>
      <div className="simple-page">
        <Container onDrop={onDrop}>
          {items.map(p => (
            <Draggable key={p.id}>
              <div className="draggable-item">
                {p.data}
              </div>
            </Draggable>
          ))}
        </Container>
      </div>
    </div>
  )
}
