// demos/vue/src/pages/simple-horizontal.vue
<template>
  <div style="margin: 50px; overflow-x: auto">
    <Container @drop="onDrop" orientation="horizontal" behaviour="contain">
      <Draggable v-for="item in items" :key="item.id">
        <div class="draggable-item-horizontal">
          {{item.data}}
        </div>
      </Draggable>
    </Container>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

const items = ref(generateItems(50, i => ({ id: i, data: 'Draggable ' + i })))

function onDrop (dropResult: DragResult) {
  items.value = applyDrag(items.value, dropResult)
}
</script>

// demos/react/src/pages/simple-horizontal.tsx
import { useCallback, useState, type CSSProperties } from 'react'
import { Container, Draggable, type DropResult } from '@likelylogic/react-smooth-dnd'
import { applyDrag, generateItems } from '@demo/shared'

interface Item {
  id: string
  data: string
}

const groupStyle: CSSProperties = {
  margin: '50px',
  overflowX: 'auto',
}

/** `orientation: horizontal`. */
export default function SimpleHorizontal () {
  const [items, setItems] = useState<Item[]>(() => generateItems(15, i => ({
    id: '2' + i,
    data: `Draggable - ${i}`,
  })))

  const onDrop = useCallback((result: DropResult) => {
    setItems(items => applyDrag(items, result))
  }, [])

  return (
    <div>
      <div style={groupStyle}>
        <Container orientation="horizontal" onDrop={onDrop}>
          {items.map(p => (
            <Draggable key={p.id}>
              <div className="draggable-item-horizontal">
                {p.data}
              </div>
            </Draggable>
          ))}
        </Container>
      </div>
    </div>
  )
}
