// demos/react/src/app/Nav.tsx
import { navigation } from '@demo/shared'

export interface NavProps {
  /** `name` of the page currently being shown. */
  selected: string
  /** Whether the nav is expanded; drives the `.open` / `.closed` class. */
  open: boolean
  onSelect: (name: string) => void
  onToggle: () => void
}

/**
 * The sidebar menu, built from the shared `navigation` manifest.
 *
 * The Vue demo wraps each item in a `<router-link>`; the React demo has no
 * router, so selection is lifted to `App` and passed back down.
 */
export default function Nav ({ selected, open, onSelect, onToggle }: NavProps) {
  const openClass = open ? 'open' : 'closed'

  return (
    <>
      {/* the hamburger is position: fixed, so it sits outside the collapsing panel */}
      <div className={`nav-button ${openClass}`} onClick={onToggle}>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>

    <div className={`nav ${openClass}`}>
      <div className="nav-content">
        <div className="nav-header">
          <h3>react-smooth-dnd</h3>
          <div className="divider"></div>
        </div>
        <div>
          {navigation.map(section => (
            <div className="menu-section" key={section.title}>
              <h4>{section.title}</h4>
              <ul>
                {section.pages.map(page => (
                  <li
                    key={page.name}
                    className={page.name === selected ? 'selected' : ''}
                    onClick={() => onSelect(page.name)}
                  >
                    {page.title}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </div>
    </>
  )
}

// demos/vue/src/app/Nav.vue
<script setup lang="ts">
import { computed } from 'vue'
import { navigation } from '@demo/shared'

const props = defineProps<{
  /** Whether the nav is expanded; owned by App.vue. */
  open: boolean
}>()

defineEmits<{
  toggle: []
}>()

const openClass = computed(() => props.open ? 'open' : 'closed')
</script>

<template>
  <!-- the hamburger is position: fixed, so it sits outside the collapsing panel -->
  <div class="nav-button" :class="openClass" @click="$emit('toggle')">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </div>

  <div class="nav" :class="openClass">
    <div class="nav-content">
      <div class="nav-header">
        <h3>vue-smooth-dnd</h3>
        <div class="divider"></div>
      </div>
      <div>
        <div v-for="section in navigation" :key="section.title" class="menu-section">
          <h4>{{ section.title }}</h4>
          <ul>
            <!-- custom render, so the active class lands on the <li> rather than an <a> -->
            <router-link
              v-for="page in section.pages"
              :key="page.name"
              :to="`/${page.name}`"
              custom
              v-slot="{ navigate, isActive }"
            >
              <li :class="{ 'router-link-active': isActive }" :title="page.description" @click="navigate">
                {{ page.title }}
              </li>
            </router-link>
          </ul>
        </div>
      </div>
    </div>
  </div>
</template>
