// demos/react/src/demo/pages/chess.jsx
import { Component } from 'react';
import { Container, Draggable } from '@likelylogic/react-smooth-dnd';

class ChessBoard extends Component {
	constructor(props) {
		super(props);
		this.initBoard = this.initBoard.bind(this);
		this.onDrop = this.onDrop.bind(this);
		this.shouldAcceptDrop = this.shouldAcceptDrop.bind(this);
		this.renderPiece = this.renderPiece.bind(this);
		this.onDragEnter = this.onDragEnter.bind(this);
		this.onDragLeave = this.onDragLeave.bind(this);

		this.state = {
			board: this.initBoard()
		}
	}

	getFirstPieceRow(side) {
		return [
			{ type: 'rook', side, data: 9816 },
			{ type: 'knight', side, data: 9814 },
			{ type: 'bishop', side, data: 9815 },
			{ type: 'queen', side, data: 9813 },
			{ type: 'king', side, data: 9812 },
			{ type: 'bishop', side, data: 9815 },
			{ type: 'knight', side, data: 9814 },
			{ type: 'rook', side, data: 9816 },
		]
	}

	getSecondPieceRow(side) {
		return [
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
			{ type: 'pawn', side, data: 9817 },
		]
	}

	initBoard() {
		const board = [];
		for (let i = 0; i < 8; i++) {
			if (i === 0) {
				board.push(this.getFirstPieceRow('black'));
			} else if (i === 1) {
				board.push(this.getSecondPieceRow('black'));
			} else if (i === 6) {
				board.push(this.getSecondPieceRow('white'));
			} else if (i === 7) {
				board.push(this.getFirstPieceRow('white'));
			} else {
				board.push([{}, {}, {}, {}, {}, {}, {}, {}]);
			}
		}

		return board;
	}

	renderPiece(piece) {
		if (piece.side) {
			const htmlcode = `&#${piece.data + (piece.side === 'black' ? 6 : 0)};`;
			const hover = piece.hover ? ' hover' : '';
			return (
				<Draggable>
					<div className={`piece${hover} ${piece.side}`}>
						<span dangerouslySetInnerHTML={{ __html: htmlcode }}></span>
					</div>
				</Draggable>
			);
		} else {
			return null;
		}
	}

	render() {
		return (
			<div className="board">
				{this.state.board.map((row, rowIndex) => {
					return (
						<div className="row" key={rowIndex}>
							{row.map((piece, colIndex) => {
								
								return (
									<div className={`square ${(rowIndex + colIndex) % 2 === 0 ? 'white' : 'black'}`} key={`${rowIndex}${colIndex}`}>
										<Container
											style={{ height: '100%' }}
											behaviour="drop-zone"
											onDrop={(result) => this.onDrop(result, rowIndex, colIndex)}
											shouldAcceptDrop={(_, payload) => this.shouldAcceptDrop(payload, rowIndex, colIndex)}
											getChildPayload={() => ({ colIndex, rowIndex, piece })}
											onDragEnter={() => this.onDragEnter(rowIndex, colIndex)}
											onDragLeave={() => this.onDragLeave(rowIndex, colIndex)}
										>
											{this.renderPiece(piece)}
										</Container>
									</div>
								);
							})}
						</div>
					);
				})}
			</div>
		);
	}

	shouldAcceptDrop(payload, rowIndex, colIndex) {
		const { colIndex: fromCol, rowIndex: fromRow } = payload;
		const fromPiece = this.state.board[fromRow][fromCol];
		const piece = this.state.board[rowIndex][colIndex];

		if (fromPiece === piece) return true;
		if (fromPiece.side === piece.side) return false;

		return true;
	}

	onDrop(dropResult, rowIndex, colIndex) {
		const { addedIndex, removedIndex, payload } = dropResult;

		if (addedIndex !== null || removedIndex !== null) {
			if (removedIndex !== null) {
				this.state.board[rowIndex][colIndex] = {};
			}

			if (addedIndex !== null) {
				this.state.board[rowIndex][colIndex] = payload.piece;
			}

			this.forceUpdate();
		}
	}

	onDragEnter(row, col) {
		this.state.board[row][col].hover = true;
		this.forceUpdate();
	}

	onDragLeave(row, col) {
		this.state.board[row][col].hover = false;
		this.forceUpdate();
	}
}

export default ChessBoard;

// demos/vue/src/pages/chess.vue
<template>
  <div class="board">
    <div v-for="(row, rowIndex) in board" :key="rowIndex" class="row">
      <div
        v-for="(piece, colIndex) in row"
        :key="`${rowIndex}${colIndex}`"
        :class="['square', (rowIndex + colIndex) % 2 === 0 ? 'white' : 'black']"
      >
        <Container
          style="height: 100%"
          behaviour="drop-zone"
          :should-accept-drop="(_source, payload) => shouldAcceptDrop(payload, rowIndex, colIndex)"
          :get-child-payload="() => ({ colIndex, rowIndex, piece })"
          @drop="onDrop($event, rowIndex, colIndex)"
          @drag-enter="onDragEnter(rowIndex, colIndex)"
          @drag-leave="onDragLeave(rowIndex, colIndex)"
        >
          <Draggable v-if="piece.side">
            <div :class="['piece', { hover: piece.hover }, piece.side]">
              <span>{{ glyph(piece) }}</span>
            </div>
          </Draggable>
        </Container>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import type { DragResult } from '@demo/shared'

type Side = 'black' | 'white'

interface Piece {
  type?: string
  side?: Side
  data?: number
  hover?: boolean
}

interface Payload {
  rowIndex: number
  colIndex: number
  piece: Piece
}

function getFirstPieceRow (side: Side): Piece[] {
  return [
    { type: 'rook', side, data: 9816 },
    { type: 'knight', side, data: 9814 },
    { type: 'bishop', side, data: 9815 },
    { type: 'queen', side, data: 9813 },
    { type: 'king', side, data: 9812 },
    { type: 'bishop', side, data: 9815 },
    { type: 'knight', side, data: 9814 },
    { type: 'rook', side, data: 9816 },
  ]
}

function getSecondPieceRow (side: Side): Piece[] {
  return Array.from({ length: 8 }, () => ({ type: 'pawn', side, data: 9817 }))
}

function initBoard (): Piece[][] {
  const board: Piece[][] = []
  for (let i = 0; i < 8; i++) {
    if (i === 0) {
      board.push(getFirstPieceRow('black'))
    }
    else if (i === 1) {
      board.push(getSecondPieceRow('black'))
    }
    else if (i === 6) {
      board.push(getSecondPieceRow('white'))
    }
    else if (i === 7) {
      board.push(getFirstPieceRow('white'))
    }
    else {
      board.push([{}, {}, {}, {}, {}, {}, {}, {}])
    }
  }
  return board
}

const board = ref<Piece[][]>(initBoard())

/** The unicode chess glyph for a piece; black pieces sit 6 code points on. */
function glyph (piece: Piece) {
  return String.fromCharCode(piece.data! + (piece.side === 'black' ? 6 : 0))
}

/** Only allow a drop onto an empty square, or one holding an opponent's piece. */
function shouldAcceptDrop (payload: unknown, rowIndex: number, colIndex: number) {
  const { colIndex: fromCol, rowIndex: fromRow } = payload as Payload
  const fromPiece = board.value[fromRow][fromCol]
  const piece = board.value[rowIndex][colIndex]

  if (fromPiece === piece) {
    return true
  }
  if (fromPiece.side === piece.side) {
    return false
  }

  return true
}

function onDrop (dropResult: DragResult, rowIndex: number, colIndex: number) {
  const { addedIndex, removedIndex, payload } = dropResult

  if (addedIndex !== null || removedIndex !== null) {
    if (removedIndex !== null) {
      board.value[rowIndex][colIndex] = {}
    }

    if (addedIndex !== null) {
      board.value[rowIndex][colIndex] = (payload as Payload).piece
    }
  }
}

function onDragEnter (row: number, col: number) {
  board.value[row][col].hover = true
}

function onDragLeave (row: number, col: number) {
  board.value[row][col].hover = false
}
</script>
