// demos/react/src/pages/groups.tsx
import { useCallback, useState, type CSSProperties } from 'react'
import { Container, Draggable, type DropResult } from '@likelylogic/react-smooth-dnd'
import { applyDrag, generateItems } from '@demo/shared'

interface Item {
  id: string
  data: string
}

const groupStyle: CSSProperties = {
  marginLeft: '50px',
  flex: 1,
}

const makeItems = (group: number) => generateItems<Item>(15, i => ({
  id: group + '' + i,
  data: `Draggable ${group} - ${i}`,
}))

/**
 * Four containers sharing a `groupName`, so items move between them.
 *
 * `getChildPayload` is what makes a cross-container move possible: the source
 * hands over the model object, and the target's `onDrop` receives it as
 * `payload`.
 */
export default function Groups () {
  const [items1, setItems1] = useState<Item[]>(() => makeItems(1))
  const [items2, setItems2] = useState<Item[]>(() => makeItems(2))
  const [items3, setItems3] = useState<Item[]>(() => makeItems(3))
  const [items4, setItems4] = useState<Item[]>(() => makeItems(4))

  const getPayload1 = useCallback((i: number) => items1[i], [items1])
  const getPayload2 = useCallback((i: number) => items2[i], [items2])
  const getPayload3 = useCallback((i: number) => items3[i], [items3])
  const getPayload4 = useCallback((i: number) => items4[i], [items4])

  const onDrop1 = useCallback((e: DropResult) => setItems1(items => applyDrag(items, e)), [])
  const onDrop2 = useCallback((e: DropResult) => setItems2(items => applyDrag(items, e)), [])
  const onDrop3 = useCallback((e: DropResult) => setItems3(items => applyDrag(items, e)), [])
  const onDrop4 = useCallback((e: DropResult) => setItems4(items => applyDrag(items, e)), [])

  const renderItems = (items: Item[]) => items.map(p => (
    <Draggable key={p.id}>
      <div className="draggable-item">
        {p.data}
      </div>
    </Draggable>
  ))

  return (
    <div style={{ display: 'flex', justifyContent: 'stretch', marginTop: '50px', marginRight: '50px' }}>
      <div style={groupStyle}>
        <Container groupName="1" getChildPayload={getPayload1} onDrop={onDrop1}>
          {renderItems(items1)}
        </Container>
      </div>
      <div style={groupStyle}>
        <Container groupName="1" getChildPayload={getPayload2} onDrop={onDrop2}>
          {renderItems(items2)}
        </Container>
      </div>
      <div style={groupStyle}>
        <Container groupName="1" getChildPayload={getPayload3} onDrop={onDrop3}>
          {renderItems(items3)}
        </Container>
      </div>
      <div style={groupStyle}>
        <Container groupName="1" getChildPayload={getPayload4} onDrop={onDrop4}>
          {renderItems(items4)}
        </Container>
      </div>
    </div>
  )
}

// demos/vue/src/pages/groups.vue
<template>
  <div class="groups">
    <div class="group">
      <Container group-name="1" :get-child-payload="getChildPayload1" @drop="onDrop1">
        <Draggable v-for="item in items1" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
    <div class="group">
      <Container group-name="1" :get-child-payload="getChildPayload2" @drop="onDrop2">
        <Draggable v-for="item in items2" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
    <div class="group">
      <Container group-name="1" :get-child-payload="getChildPayload3" @drop="onDrop3">
        <Draggable v-for="item in items3" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
    <div class="group">
      <Container group-name="1" :get-child-payload="getChildPayload4" @drop="onDrop4">
        <Draggable v-for="item in items4" :key="item.id">
          <div class="draggable-item">
            {{item.data}}
          </div>
        </Draggable>
      </Container>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

interface Item {
  id: string
  data: string
}

const items1 = ref<Item[]>(generateItems(15, i => ({
  id: '1' + i,
  data: `Draggable 1 - ${i}`,
})))

const items2 = ref<Item[]>(generateItems(15, i => ({
  id: '2' + i,
  data: `Draggable 2 - ${i}`,
})))

const items3 = ref<Item[]>(generateItems(15, i => ({
  id: '3' + i,
  data: `Draggable 3 - ${i}`,
})))

const items4 = ref<Item[]>(generateItems(15, i => ({
  id: '4' + i,
  data: `Draggable 3 - ${i}`,
})))

function onDrop1 (dropResult: DragResult) {
  items1.value = applyDrag(items1.value, dropResult)
}

function onDrop2 (dropResult: DragResult) {
  items2.value = applyDrag(items2.value, dropResult)
}

function onDrop3 (dropResult: DragResult) {
  items3.value = applyDrag(items3.value, dropResult)
}

function onDrop4 (dropResult: DragResult) {
  items4.value = applyDrag(items4.value, dropResult)
}

function getChildPayload1 (index: number) {
  return items1.value[index]
}

function getChildPayload2 (index: number) {
  return items2.value[index]
}

function getChildPayload3 (index: number) {
  return items3.value[index]
}

function getChildPayload4 (index: number) {
  return items4.value[index]
}
</script>

<style lang="css" scoped>
  .groups {
    display: flex;
    justify-content: stretch;
    margin-top: 50px;
    margin-right: 50px;
  }

  .group {
    margin-left: 50px;
    flex: 1;
  }
</style>
