// demos/react/src/pages/nested.tsx
import { useCallback, useState, type CSSProperties } from 'react'
import { Container, Draggable, type DropResult } from '@likelylogic/react-smooth-dnd'
import { applyDrag, generateItems } from '@demo/shared'

interface LeafNode {
  id: number
  type: 'draggable'
  data: string
}

interface BranchNode {
  id: number
  type: 'container'
  items: TreeNode[]
}

type TreeNode = LeafNode | BranchNode

const branchStyle: CSSProperties = {
  padding: '20px 20px',
  marginTop: '2px',
  marginBottom: '2px',
  border: '1px solid rgba(0,0,0,.125)',
  backgroundColor: '#fff',
  cursor: 'move',
}

const nestedBranchStyle: CSSProperties = {
  ...branchStyle,
  backgroundColor: 'cornsilk',
}

function createTree (): TreeNode[] {
  const items = generateItems<TreeNode>(30, i => ({
    id: i,
    type: 'draggable',
    data: `Container 1 Draggable - ${i}`,
  }))

  const items2 = generateItems<TreeNode>(10, i => ({
    id: i,
    type: 'draggable',
    data: `Container 2 Draggable - ${i}`,
  }))

  items2[3] = {
    id: 3,
    type: 'container',
    items: generateItems<TreeNode>(4, i => ({
      id: i,
      type: 'draggable',
      data: `Container 4 Draggable - ${i}`,
    })),
  }

  const items3 = generateItems<TreeNode>(4, i => ({
    id: i,
    type: 'draggable',
    data: `Container 3 Draggable - ${i}`,
  }))

  items[5] = { id: 5, type: 'container', items: items2 }
  items[9] = { id: 9, type: 'container', items: items3 }

  return items
}

/**
 * A sortable container inside a sortable container, three levels deep.
 *
 * No `groupName` here, so each level is its own island: items reorder within
 * their own list and can't cross a boundary. `nested-group` is the case where
 * they can.
 */
export default function Nested () {
  const [items, setItems] = useState<TreeNode[]>(createTree)

  const onDrop = useCallback((e: DropResult) => {
    setItems(items => applyDrag(items, e))
  }, [])

  const onDrop2 = useCallback((index: number, e: DropResult) => {
    setItems(items => items.map((item, i) => (
      i === index && item.type === 'container'
        ? { ...item, items: applyDrag(item.items, e) }
        : item
    )))
  }, [])

  const onDrop3 = useCallback((index1: number, index2: number, e: DropResult) => {
    setItems(items => items.map((item, i) => {
      if (i !== index1 || item.type !== 'container') {
        return item
      }
      return {
        ...item,
        items: item.items.map((child, j) => (
          j === index2 && child.type === 'container'
            ? { ...child, items: applyDrag(child.items, e) }
            : child
        )),
      }
    }))
  }, [])

  return (
    <div>
      <div className="simple-page">
        <Container onDrop={onDrop}>
          {items.map((p, i) => p.type === 'draggable'
            ? (
                <Draggable key={i}>
                  <div className="draggable-item">{p.data}</div>
                </Draggable>
              )
            : (
                <Draggable key={i}>
                  <div style={branchStyle}>
                    <h4 style={{ textAlign: 'center' }}>
                      Nested Sortable List - {p.id}
                    </h4>
                    <div style={{ cursor: 'default' }}>
                      <Container onDrop={e => onDrop2(i, e)}>
                        {p.items.map((q, j) => q.type === 'draggable'
                          ? (
                              <Draggable key={j}>
                                <div className="draggable-item" style={{ backgroundColor: 'cornsilk' }}>
                                  {q.data}
                                </div>
                              </Draggable>
                            )
                          : (
                              <Draggable key={j}>
                                <div style={nestedBranchStyle}>
                                  <h4 style={{ textAlign: 'center' }}>
                                    Nested Sortable List - {q.id}
                                  </h4>
                                  <div style={{ cursor: 'default' }}>
                                    <Container onDrop={e => onDrop3(i, j, e)}>
                                      {q.items.map((t, y) => (
                                        <Draggable key={y}>
                                          <div className="draggable-item" style={{ backgroundColor: 'ghostwhite' }}>
                                            {t.type === 'draggable' ? t.data : null}
                                          </div>
                                        </Draggable>
                                      ))}
                                    </Container>
                                  </div>
                                </div>
                              </Draggable>
                            ))}
                      </Container>
                    </div>
                  </div>
                </Draggable>
              ))}
        </Container>
      </div>
    </div>
  )
}

// demos/vue/src/pages/nested.vue
<template>
  <div class="simple-page">
    <Container @drop="onDrop($event)">
      <Draggable v-for="item in items" :key="item.id">
        <div v-if="item.type === 'draggable'" class="draggable-item">
          {{item.data}}
        </div>
        <div v-if="item.type === 'container'">
          <div :style="innerContainerStyle">
            <h4>Sortable List</h4>
            <div class="no-cursor">
              <Container @drop="onInnerDrop(item, $event)">
                <Draggable v-for="q in item.items" :key="q.id">
                  <div v-if="q.type === 'draggable'" class="draggable-item">
                    {{q.data}}
                  </div>
                  <div v-if="q.type === 'container'">
                    <div :style="innerContainerStyle">
                      <h4>Sortable List</h4>
                      <div class="no-cursor">
                        <Container @drop="onInnerDrop2(item, q, $event)">
                          <Draggable v-for="t in q.items" :key="t.id">
                            <div class="draggable-item">
                              {{t.data}}
                            </div>
                          </Draggable>
                        </Container>
                      </div>
                    </div>
                  </div>
                </Draggable>
              </Container>
            </div>
          </div>
        </div>
      </Draggable>
    </Container>
  </div>
</template>

<script setup lang="ts">
import { ref, type CSSProperties } from 'vue'
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems, type DragResult } from '@demo/shared'

interface NestedItem {
  id: number
  type: 'draggable' | 'container'
  data?: string
  items?: NestedItem[]
}

function build (): NestedItem[] {
  const items = generateItems<NestedItem>(30, i => ({
    id: i,
    type: 'draggable',
    data: `Container 1 Draggable - ${i}`,
  }))

  const items2 = generateItems<NestedItem>(10, i => ({
    id: i,
    type: 'draggable',
    data: `Container 2 Draggable - ${i}`,
  }))

  const items3 = generateItems<NestedItem>(4, i => ({
    id: i,
    type: 'draggable',
    data: `Container 3 Draggable - ${i}`,
  }))

  items[5] = {
    id: 5,
    type: 'container',
    items: items2,
  }

  items[5].items![3] = {
    id: 3,
    type: 'container',
    items: generateItems<NestedItem>(4, i => ({
      id: i,
      type: 'draggable',
      data: `Container 4 Draggable - ${i}`,
    })),
  }

  items[9] = {
    id: 9,
    type: 'container',
    items: items3,
  }

  return items
}

const items = ref<NestedItem[]>(build())

const innerContainerStyle: CSSProperties = {
  padding: '20px 20px',
  marginTop: '2px',
  marginBottom: '2px',
  border: '1px solid rgba(0,0,0,.125)',
  backgroundColor: '#f4f5f9aa',
  cursor: 'move',
}

function onDrop (dropResult: DragResult) {
  items.value = applyDrag(items.value, dropResult)
}

function onInnerDrop (item: NestedItem, dropResult: DragResult) {
  const newItems = [...items.value]
  const index = newItems.indexOf(item)
  newItems[index].items = applyDrag(newItems[index].items!, dropResult)
  items.value = newItems
}

function onInnerDrop2 (item: NestedItem, item2: NestedItem, dropResult: DragResult) {
  const newItems = [...items.value]
  const index = newItems.indexOf(item)
  const index2 = item.items!.indexOf(item2)
  newItems[index].items![index2].items = applyDrag(
    newItems[index].items![index2].items!,
    dropResult,
  )
  items.value = newItems
}
</script>

<style lang="css" scoped>
  .no-cursor {
    cursor: default;
  }
</style>
