// demos/react/src/demo/pages/nested.jsx
import { Component } from 'react';
import { Container, Draggable } from '@likelylogic/react-smooth-dnd';
import { applyDrag, generateItems } from './utils.js';

class Nested extends Component {
  constructor(props) {
    super(props);

    this.containerOnDrop = this.containerOnDrop.bind(this);
    this.containerOnDrop2 = this.containerOnDrop2.bind(this);
    this.containerOnDrop3 = this.containerOnDrop3.bind(this);

    const items = generateItems(30, i => ({
      id: i,
      type: "draggable",
      data: `Container 1 Draggable - ${i}`
    }));

    const items2 = generateItems(10, i => ({
      id: i,
      type: "draggable",
      data: `Container 2 Draggable - ${i}`
    }));

    items2[3] = {
      id: 3,
      type: "container",
      items: generateItems(4, i => ({
        id: i,
        type: "draggable",
        data: `Container 4 Draggable - ${i}`
      }))
    };

    const items3 = generateItems(4, i => ({
      id: i,
      type: "draggable",
      data: `Container 3 Draggable - ${i}`
    }));

    items[5] = {
      id: 5,
      type: "container",
      items: items2
    };

    items[9] = {
      id: 9,
      type: "container",
      items: items3
    };

    this.state = {
      items
    };
  }
  render() {
    return (
      <div>
        <div className="simple-page">
          <Container onDrop={this.containerOnDrop}>
            {this.state.items.map((p, i) => {
              if (p.type === "draggable") {
                return (
                  <Draggable key={i}>
                    <div className="draggable-item">{p.data}</div>
                  </Draggable>
                );
              } else {
                return (
                  <Draggable key={i}>
                    <div
                      style={{
                        padding: "20px 20px",
                        marginTop: "2px",
                        marginBottom: "2px",
                        border: "1px solid rgba(0,0,0,.125)",
                        backgroundColor: "#fff",
                        cursor: "move"
                      }}
                    >
                      <h4 style={{ textAlign: "center" }}>
                        Nested Sortable List - {p.id}
                      </h4>
                      <div style={{ cursor: "default" }}>
                        <Container onDrop={e => this.containerOnDrop2(i, e)}>
                          {p.items.map((q, j) => {
                            if (q.type === "draggable") {
                              return (
                                <Draggable key={j}>
                                  <div
                                    className="draggable-item"
                                    style={{ backgroundColor: "cornsilk" }}
                                  >
                                    {q.data}
                                  </div>
                                </Draggable>
                              );
                            } else {
                              return (
                                <Draggable key={j}>
                                  <div
                                    style={{
                                      padding: "20px 20px",
                                      marginTop: "2px",
                                      marginBottom: "2px",
                                      border: "1px solid rgba(0,0,0,.125)",
                                      backgroundColor: "cornsilk",
                                      cursor: "move"
                                    }}
                                  >
                                    <h4
                                      style={{
                                        textAlign: "center"
                                      }}
                                    >
                                      Nested Sortable List - {q.id}
                                    </h4>
                                    <div style={{ cursor: "default" }}>
                                      <Container
                                        onDrop={e =>
                                          this.containerOnDrop3(i, j, e)
                                        }
                                      >
                                        {q.items.map((t, y) => {
                                          return (
                                            <Draggable key={y}>
                                              <div
                                                className="draggable-item"
                                                style={{
                                                  backgroundColor: "ghostwhite"
                                                }}
                                              >
                                                {t.data}
                                              </div>
                                            </Draggable>
                                          );
                                        })}
                                      </Container>
                                    </div>
                                  </div>
                                </Draggable>
                              );
                            }
                          })}
                        </Container>
                      </div>
                    </div>
                  </Draggable>
                );
              }
            })}
          </Container>
        </div>
      </div>
    );
  }

  containerOnDrop(e) {
    this.setState({
      items: applyDrag(this.state.items, e)
    });
  }

  containerOnDrop2(id, e) {
    const newItems = [...this.state.items];
    newItems[id].items = applyDrag(newItems[id].items, e);
    this.setState({
      items: newItems
    });
  }

  containerOnDrop3(id1, id2, e) {
    const newItems = [...this.state.items];
    newItems[id1].items[id2].items = applyDrag(
      newItems[id1].items[id2].items,
      e
    );
    this.setState({
      items: newItems
    });
  }
}

export default Nested;

// demos/vue/src/pages/nested.vue
<template>
  <div class="simple-page">
    <Container @drop="onDrop($event)">
      <Draggable v-for="item in items" :key="item.id">
        <div v-if="item.type === 'draggable'" class="draggable-item">
          {{item.data}}
        </div>
        <div v-if="item.type === 'container'">
          <div :style="innerContainerStyle">
            <h4>Sortable List</h4>
            <div class="no-cursor">
              <Container @drop="onInnerDrop(item, $event)">
                <Draggable v-for="q in item.items" :key="q.id">
                  <div v-if="q.type === 'draggable'" class="draggable-item">
                    {{q.data}}
                  </div>
                  <div v-if="q.type === 'container'">
                    <div :style="innerContainerStyle">
                      <h4>Sortable List</h4>
                      <div class="no-cursor">
                        <Container @drop="onInnerDrop2(item, q, $event)">
                          <Draggable v-for="t in q.items" :key="t.id">
                            <div class="draggable-item">
                              {{t.data}}
                            </div>
                          </Draggable>
                        </Container>
                      </div>
                    </div>
                  </div>
                </Draggable>
              </Container>
            </div>
          </div>
        </div>
      </Draggable>
    </Container>
  </div>
</template>

<script>
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems } from '../utils/helpers'

export default {
  name: 'Nested',

  components: {Container, Draggable},

  data () {
    const res = {
      items: generateItems(30, i => ({
        id: i,
        type: 'draggable',
        data: `Container 1 Draggable - ${i}`
      })),
      items2: generateItems(10, i => ({
        id: i,
        type: 'draggable',
        data: `Container 2 Draggable - ${i}`
      })),
      items3: generateItems(4, i => ({
        id: i,
        type: 'draggable',
        data: `Container 3 Draggable - ${i}`
      })),
      innerContainerStyle: {
        padding: '20px 20px',
        marginTop: '2px',
        marginBottom: '2px',
        border: '1px solid rgba(0,0,0,.125)',
        backgroundColor: '#f4f5f9aa',
        cursor: 'move'
      }
    }

    res.items[5] = {
      id: 5,
      type: 'container',
      items: res.items2
    }

    res.items[5].items[3] = {
      id: 3,
      type: 'container',
      items: generateItems(4, i => ({
        id: i,
        type: 'draggable',
        data: `Container 4 Draggable - ${i}`
      }))
    }

    res.items[9] = {
      id: 9,
      type: 'container',
      items: res.items3
    }

    return res
  },
  methods: {
    onDrop (dropResult) {
      this.items = applyDrag(this.items, dropResult)
    },

    onInnerDrop (item, dropResult) {
      const newItems = [...this.items]
      const index = newItems.indexOf(item)
      newItems[index].items = applyDrag(newItems[index].items, dropResult)
      this.items = newItems
    },

    onInnerDrop2 (item, item2, dropResult) {
      const newItems = [...this.items]
      const index = newItems.indexOf(item)
      const index2 = item.items.indexOf(item2)
      newItems[index].items[index2].items = applyDrag(
        newItems[index].items[index2].items,
        dropResult
      )
      this.items = newItems
    }
  }
}
</script>

<style lang="css" scoped>
  .no-cursor {
    cursor: default;
  }
</style>
