// demos/react/src/demo/pages/simple-horizontal.jsx
import { Component } from 'react';
import { Container, Draggable } from '@likelylogic/react-smooth-dnd';
import { applyDrag, generateItems } from './utils.js';

const groupStyle = {
  margin: '50px',
  overflowX: 'auto',
  // border: '1px solid #ccc'
};

class SimpleHorizontal extends Component {
  constructor(props) {
    super(props);
    this.state = {
      items: generateItems(15, (i) => ({ id: '2' + i, data: `Draggable - ${i}` })),
    };
  }
  render() {
    return (
      <div>
        <div style={groupStyle}>
          <Container orientation="horizontal" onDrop={e => this.setState({ items: applyDrag(this.state.items, e) })}>
            {
              this.state.items.map(p => {
                return (
                  <Draggable key={p.id}>
                    <div className="draggable-item-horizontal">
                      {p.data}
                    </div>
                  </Draggable>
                );
              })
            }
          </Container>
        </div>
      </div>
    );
  }
}

export default SimpleHorizontal;

// demos/vue/src/pages/simple-horizontal.vue
<template>
  <div style="margin: 50px; overflow-x: auto">
    <Container @drop="onDrop" orientation="horizontal" behaviour="contain">
      <Draggable v-for="item in items" :key="item.id">
        <div class="draggable-item-horizontal">
          {{item.data}}
        </div>
      </Draggable>
    </Container>
  </div>
</template>

<script>
import { Container, Draggable } from '@likelylogic/vue-smooth-dnd'
import { applyDrag, generateItems } from '../utils/helpers'

export default {
  name: 'SimpleHorizontal',

  components: {Container, Draggable},

  data () {
    return {
      items: generateItems(50, i => ({id: i, data: 'Draggable ' + i}))
    }
  },

  methods: {
    onDrop (dropResult) {
      this.items = applyDrag(this.items, dropResult)
    }
  }
}
</script>
